import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service | Act 60 Review',
  description: 'Terms of Service for Act 60 Review, operated by Dis Optimus Capital LLC.',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-navy-900 pt-28 pb-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/" className="text-gold/60 text-sm hover:text-gold transition-colors mb-8 inline-block">&larr; Back to Home</Link>

        <h1 className="font-serif text-4xl sm:text-5xl text-slate-100 mb-4 tracking-tight">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-12">Last updated: March 16, 2026</p>

        <div className="prose-custom space-y-8 text-slate-400 text-[15px] leading-relaxed">
          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using the Act 60 Review service (&ldquo;Service&rdquo;), operated by Dis Optimus Capital LLC (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), a Puerto Rico limited liability company, you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, you may not access or use the Service.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">2. Description of Service</h2>
            <p>Act 60 Review provides AI-assisted analysis of tax returns and related documents for Puerto Rico Act 60 decree holders. The Service uses artificial intelligence technology combined with professional CPA review to identify potential compliance issues. The Service is an informational and educational tool only.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">3. Not Professional Advice</h2>
            <p className="font-semibold text-slate-300">THE SERVICE DOES NOT CONSTITUTE TAX PREPARATION, TAX ADVICE, LEGAL ADVICE, OR REPRESENTATION BEFORE THE IRS, PUERTO RICO DEPARTMENT OF TREASURY (HACIENDA), OR ANY OTHER GOVERNMENT AGENCY.</p>
            <p className="mt-3">The Service is not a substitute for consultation with a licensed Certified Public Accountant (CPA), enrolled agent, or tax attorney. No professional-client, attorney-client, or fiduciary relationship is created by your use of the Service. You should not rely solely on the Service&apos;s outputs when making tax decisions. Always consult a qualified professional before acting on any information provided by the Service.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">4. User Responsibilities</h2>
            <p>You represent and warrant that: (a) you are at least 18 years of age; (b) any documents or information you provide are yours or you have authorization to share them; (c) the information you provide is accurate and complete; and (d) your use of the Service complies with all applicable laws and regulations.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">5. Payment and Refund Policy</h2>
            <p>Payments are processed securely through Stripe. All fees are stated in U.S. dollars. You agree to pay the applicable fees for the tier of service you select. We offer a full refund within seven (7) days of receiving your report, no questions asked. Refund requests must be submitted via email to support@act60review.com. Refunds are processed within 5-10 business days.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">6. Intellectual Property</h2>
            <p>All content, technology, algorithms, software, design, and materials on the Service are the exclusive property of Dis Optimus Capital LLC or its licensors. You are granted a limited, non-exclusive, non-transferable license to access and use the Service for your personal, non-commercial compliance review purposes. Your uploaded tax documents remain your property. Reports generated by the Service are licensed to you for personal use only and may not be redistributed, resold, or published without our written consent.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">7. Limitation of Liability</h2>
            <p className="font-semibold text-slate-300">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL DIS OPTIMUS CAPITAL LLC, ITS OFFICERS, DIRECTORS, MEMBERS, EMPLOYEES, AGENTS, CONTRACTORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR USE, WHETHER IN AN ACTION IN CONTRACT, TORT, OR OTHERWISE, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.</p>
            <p className="mt-3">OUR AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
            <p className="mt-3">YOU ACKNOWLEDGE THAT THE SERVICE PROVIDES INFORMATIONAL OUTPUT BASED ON AI ANALYSIS AND THAT NO AI SYSTEM IS INFALLIBLE. THE COMPANY MAKES NO GUARANTEE THAT THE SERVICE WILL IDENTIFY ALL COMPLIANCE ISSUES OR THAT ITS ANALYSIS WILL BE FREE FROM ERROR.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">8. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR COMPLETENESS. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">9. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless Dis Optimus Capital LLC, its officers, directors, members, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or in any way connected with: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any tax positions you take based on the Service&apos;s output.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">10. Dispute Resolution and Arbitration</h2>
            <p>Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved through binding arbitration administered by the American Arbitration Association (&ldquo;AAA&rdquo;) under its Commercial Arbitration Rules. The arbitration shall be conducted by a single arbitrator in San Juan, Puerto Rico. The arbitrator&apos;s decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction.</p>
            <p className="mt-3">YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. You waive any right to participate in a class action lawsuit or class-wide arbitration.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">11. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of the Commonwealth of Puerto Rico, without regard to its conflict of laws provisions. Any legal proceedings not subject to the arbitration clause above shall be brought exclusively in the courts of Puerto Rico, and you consent to the personal jurisdiction of such courts.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">12. Data Handling</h2>
            <p>Your use of the Service is also governed by our <Link href="/privacy" className="text-gold hover:text-gold-light transition-colors">Privacy Policy</Link>, which is incorporated into these Terms by reference. By using the Service, you consent to the collection and use of your information as described in the Privacy Policy.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">13. Modifications</h2>
            <p>We reserve the right to modify these Terms at any time. Material changes will be posted on this page with an updated effective date. Your continued use of the Service after any changes constitutes acceptance of the modified Terms.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">14. Termination</h2>
            <p>We may suspend or terminate your access to the Service at any time, for any reason, without notice. Upon termination, your right to use the Service ceases immediately. Sections 3, 6, 7, 8, 9, 10, and 11 shall survive termination.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">15. Contact</h2>
            <p>For questions about these Terms, contact:</p>
            <p className="mt-2 text-slate-300">
              Dis Optimus Capital LLC<br />
              San Juan, Puerto Rico<br />
              support@act60review.com
            </p>
          </section>
        </div>
      </div>
    </main>
  )
}
