import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Disclaimer | Act 60 Review',
  description: 'Legal disclaimer for Act 60 Review, operated by Dis Optimus Capital LLC.',
}

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-navy-900 pt-28 pb-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/" className="text-accent/60 text-sm hover:text-accent transition-colors mb-8 inline-block">&larr; Back to Home</Link>

        <h1 className="font-serif text-4xl sm:text-5xl text-slate-100 mb-4 tracking-tight">Disclaimer</h1>
        <p className="text-sm text-slate-500 mb-12">Last updated: March 16, 2026</p>

        <div className="space-y-8 text-slate-400 text-[15px] leading-relaxed">
          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Important Notice</h2>
            <p className="text-slate-300 font-semibold">Please read this disclaimer carefully before using the Act 60 Review service. By using this Service, you acknowledge that you have read, understood, and agree to the following terms.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Not Tax Advice</h2>
            <p>Act 60 Review, operated by Dis Optimus Capital LLC, is an AI-assisted informational tool. <span className="text-slate-300 font-semibold">The Service does not provide tax advice, legal advice, accounting services, or any form of professional counsel.</span> The outputs, reports, compliance scores, and recommendations generated by the Service are for informational and educational purposes only and should not be construed as professional advice of any kind.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Not Tax Preparation</h2>
            <p>The Service does not prepare, file, amend, or submit tax returns or any tax-related documents on your behalf. The Service does not sign any tax forms or elections. Use of the Service does not constitute &ldquo;tax return preparation&rdquo; as defined under 26 CFR 301.7701-15, IRS Circular 230, or Puerto Rico Law No. 293 of 1945 (as amended). The Service is a review and analysis tool only.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">No Professional Relationship</h2>
            <p>Use of the Service does not create a CPA-client, attorney-client, advisor-client, or any other professional-client relationship between you and Dis Optimus Capital LLC, its officers, members, employees, contractors, or affiliated CPA reviewers. CPA reviewers who verify AI findings as part of the Service do so in a quality assurance capacity for the Company, not as your personal CPA or advisor.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">No Representation Before Government Agencies</h2>
            <p>The Service does not represent you before the Internal Revenue Service (IRS), the Puerto Rico Department of Treasury (Hacienda), or any other federal, state, or territorial government agency. If you are currently under audit or investigation, you should consult with a licensed tax attorney or CPA who can represent you before the relevant agency.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">AI Limitations</h2>
            <p>The Service uses artificial intelligence and machine learning technology to analyze tax documents. While we strive for accuracy, <span className="text-slate-300 font-semibold">no AI system is infallible.</span> The Service may:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
              <li>Fail to identify certain compliance issues</li>
              <li>Generate false positive findings</li>
              <li>Misinterpret data from documents with poor quality, unusual formatting, or non-standard entries</li>
              <li>Not reflect the most recent changes to tax law, IRS guidance, or Hacienda regulations</li>
            </ul>
            <p className="mt-3">You should always verify the Service&apos;s findings with a qualified tax professional before taking any action.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">No Guarantee</h2>
            <p>Dis Optimus Capital LLC makes no guarantee, representation, or warranty that:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
              <li>The Service will identify all compliance issues in your tax return</li>
              <li>Use of the Service will prevent an IRS or Hacienda audit</li>
              <li>Use of the Service will reduce any tax liability, penalty, or interest</li>
              <li>The compliance score or findings are free from error</li>
              <li>The Service is a substitute for professional CPA or legal counsel</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Assumption of Risk</h2>
            <p>You use the Service at your own risk. You are solely responsible for all tax positions taken on your returns, regardless of whether the Service identified or failed to identify any issues. Tax compliance is ultimately your responsibility and that of your licensed tax professionals.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Third-Party Information</h2>
            <p>The Service may reference government reports, legal citations, regulatory guidance, and statistical data. While we endeavor to ensure accuracy, we do not guarantee the accuracy, completeness, or currency of any third-party information. Government statistics and regulatory interpretations may change without notice.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Regulatory Compliance</h2>
            <p>The Service operates in compliance with applicable Puerto Rico and federal regulations. The Company is registered in Puerto Rico and operates under the laws of the Commonwealth of Puerto Rico. For the full terms governing your use of the Service, please review our <Link href="/terms" className="text-accent hover:text-accent-light transition-colors">Terms of Service</Link> and <Link href="/privacy" className="text-accent hover:text-accent-light transition-colors">Privacy Policy</Link>.</p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-slate-200 mb-3">Contact</h2>
            <p>If you have questions about this disclaimer:</p>
            <p className="mt-2 text-slate-300">
              Dis Optimus Capital LLC<br />
              San Juan, Puerto Rico<br />
              support@act60review.com
            </p>
          </section>
        </div>
      </div>
    </main>
  )
}
